Add electron and electron-forge. Implements #41 (#42)
Add electron support so the app can be bundled into distributable
binaries across operating systems via electron-forge. Also update the
look and feel to be more app-like.

TODO list:
 - [x] loading screen when app launches
- [x] splash screen when done loading. should display logo and menu
(start, settings, editor, about, quit)
 - [x] use icon for binaries
- [x] create binaries for windows, linux and macOS during build and
store them as release artifacts

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -1,4 +1,4 @@
-name: Test
+name: Verify
 on:
   pull_request:
     branches:
@@ -6,6 +6,9 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    outputs:
+      tag: ${{ steps.project-version.outputs.tag }}
+      version: ${{ steps.project-version.outputs.version }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -21,3 +24,47 @@ jobs:
         run: npx wait-on --timeout 5000 http://localhost:1234
       - name: Run tests
         run: npm test
+      - name: Verify project version
+        id: project-version
+        run: |
+          VERSION=$(jq -r '.version' package.json)
+          echo "Found version: $VERSION"
+          TAG="v${VERSION}"
+          if git tag -l "$TAG" | grep -q "$TAG"; then
+            echo "Error: Tag $TAG already exists."
+            exit 1
+          fi
+          echo "TAG=$TAG" >> "$GITHUB_ENV"
+          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+      # TODO: include tag in build (e.g. to display to user)
+      - name: Generate build
+        run: npm run build
+      - name: Upload build archive
+        uses: actions/upload-artifact@v4
+        with:
+          name: beaming-web
+          path: dist
+          compression-level: '9'
+  build:
+    strategy:
+      matrix:
+        os: [macos-latest, ubuntu-latest, windows-latest]
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version-file: '.nvmrc'
+      - name: Install dependencies
+        run: npm install
+      - name: "Make: ${{ matrix.os }}"
+        run: npm run make
+      - name: Upload build artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: beaming-${{ matrix.os }}
+          path: out/make/**/*
+          compression-level: '0'
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,8 +4,11 @@ on:
     branches:
       - main
 jobs:
-  release:
+  build-web:
     runs-on: ubuntu-latest
+    outputs:
+      tag: ${{ steps.project-version.outputs.tag }}
+      version: ${{ steps.project-version.outputs.version }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -23,11 +26,91 @@ jobs:
         run: npx wait-on --timeout 5000 http://localhost:1234
       - name: Run tests
         run: npm test
-      - name: Build NPM package
-        run: npm run build
+      - name: Verify project version
+        id: project-version
+        run: |
+          VERSION=$(jq -r '.version' package.json)
+          echo "Found version: $VERSION"
+          TAG="v${VERSION}"
+          if git tag -l "$TAG" | grep -q "$TAG"; then
+            echo "Error: Tag $TAG already exists."
+            exit 1
+          fi
+          echo "TAG=$TAG" >> "$GITHUB_ENV"
+          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+      # TODO: include tag in build (e.g. to display to user)
+      - name: Build for Github pages
+        run: npm run build -- --public-url https://kflorence.github.io/beaming
       - name: Publish to Github pages
         run: |
           git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
           npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>" --nojekyll
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Generate build
+        run: npm run build
+      - name: Upload build archive
+        id: artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: beaming
+          path: dist
+          compression-level: '9'
+  build-app:
+    strategy:
+      matrix:
+        os: [macos-latest, ubuntu-latest, windows-latest]
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version-file: '.nvmrc'
+      - name: Install dependencies
+        run: npm install
+      - name: "Make: ${{ matrix.os }}"
+        run: npm run make
+      - name: Upload build artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.os }}
+          path: out/make/**/*
+          compression-level: '0'
+  release:
+    runs-on: ubuntu-latest
+    needs: [build-web, build-app]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Download artifacts
+        uses: actions/download-artifact@v5
+        with:
+          path: artifacts
+      - name: List artifacts
+        run: tree artifacts
+      - name: Prepare release artifacts
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          TAG: ${{ needs.build-web.outputs.tag }}
+          VERSION: ${{ needs.build-web.outputs.version }}
+        run: |
+          shopt -s globstar
+          BASE_PATH=$(pwd)
+          mkdir release
+          mv artifacts/beaming-macos-latest/**/*.dmg release
+          mv artifacts/beaming-ubuntu-latest/**/*.{deb,rpm} release
+          cd artifacts/beaming-web
+          zip -r "${BASE_PATH}/release/beaming-${VERSION}.zip" .
+          cd "$BASE_PATH"
+          cd artifacts/beaming-windows-latest/squirrel.windows/x64
+          zip -r "${BASE_PATH}/release/beaming-${VERSION}-win.x64.zip" .
+          cd "$BASE_PATH"
+          tree release
+      - name: Create release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          TAG: ${{ needs.test.outputs.tag }}
+        run: gh release create "$TAG" ./release/* --draft --generate-notes --title "$TAG"
