Add build zip archive. Use DMG for macOS instead of ZIP
Everything will be zipped when archived anyways. Started on release
but it's still a WIP

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,8 +4,10 @@ on:
     branches:
       - main
 jobs:
-  release:
+  build-web:
     runs-on: ubuntu-latest
+    outputs:
+      tag: ${{ steps.project-version.outputs.tag }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -23,7 +25,20 @@ jobs:
         run: npx wait-on --timeout 5000 http://localhost:1234
       - name: Run tests
         run: npm test
-      - name: Build NPM package
+      - name: Verify project version
+        id: project-version
+        run: |
+          VERSION=$(jq -r '.version' package.json)
+          echo "Found version: $VERSION"
+          TAG="v${VERSION}"
+          if git tag -l "$TAG" | grep -q "$TAG"; then
+            echo "Error: Tag $TAG already exists."
+            exit 1
+          fi
+          echo "TAG=$TAG" >> "$GITHUB_ENV"
+          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
+      # TODO: include tag in build (e.g. to display to user)
+      - name: Build for Github pages
         run: npm run build -- --public-url https://kflorence.github.io/beaming
       - name: Publish to Github pages
         run: |
@@ -31,3 +46,43 @@ jobs:
           npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>" --nojekyll
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Generate build
+        run: npm run build
+      - name: Upload build archive
+        id: artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: beaming
+          path: dist
+          compression-level: '9'
+  build-app:
+    strategy:
+      matrix:
+        os: [macos-latest, ubuntu-latest, windows-latest]
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version-file: '.nvmrc'
+      - name: Install dependencies
+        run: npm install
+      - name: "Make: ${{ matrix.os }}"
+        run: npm run make
+      - name: Upload build artifacts
+        id: artifacts-${{ matrix.os }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.os }}
+          path: out/make/**/*
+          compression-level: '0'
+  release:
+    runs-on: ubuntu-latest
+    needs: [build-web, build-app]
+    steps:
+      - env:
+          TAG: ${{ needs.build-web.outputs.tag }}
+      - run: |
+          # TODO: do the release
