test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -22,39 +22,59 @@ jobs:
           # https://github.com/actions/checkout/issues/2199
           fetch-depth: 0
           fetch-tags: true
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version-file: '.nvmrc'
-      - name: Install dependencies
-        run: npm install
-      - name: Run server
-        run: npm start &
-      - name: Wait
-        run: npx wait-on --timeout 5000 http://localhost:1234
-      - name: Run tests
-        run: npm test
-      - name: Verify project version
-        id: project-version
-        run: |
-          VERSION=$(jq -r '.version' package.json)
-          echo "Found version: $VERSION"
-          TAG="v${VERSION}"
-          if git tag -l "$TAG" | grep -q "$TAG"; then
-            echo "Error: Tag $TAG already exists."
-            exit 1
-          fi
-          echo "Tag $TAG does not exist, proceeding."
-          echo "TAG=$TAG" >> "$GITHUB_ENV"
-          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
-          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
-      - name: Generate build
+      - run: |
+          TAG=$(git describe --tags --abbrev=0)
+          echo "Deploying from tag: $TAG"
+          echo "TAG=$TAG" >> $GITHUB_ENV
+      - name: Download release artifacts
         env:
-          NODE_ENV: ${{ vars.NODE_ENV }}
-        run: npm run build
-      - name: Upload build archive
-        uses: actions/upload-artifact@v4
-        with:
-          name: web
-          path: dist
-          compression-level: '9'
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh release download "$TAG" --dir artifacts
+          tree artifacts
+          shopt -s globstar
+          mkdir -p deploy/windows-ia32
+          mv release/*-win32-ia32-*.exe deploy/windows-ia32/beaming.exe
+          mkdir -p deploy/windows-x64
+          mv release/*-win32-x64-*.exe deploy/windows-x64/beaming.exe
+          mkdir -p deploy/macos-arm64
+          unzip release/*-darwin-arm64-*.zip deploy/macos-arm64
+          mkdir -p deploy/macos-x64
+          unzip release/*-darwin-x64-*.zip deploy/macos-x64
+          tree deploy
+#      - name: Setup Node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version-file: '.nvmrc'
+#      - name: Install dependencies
+#        run: npm install
+#      - name: Run server
+#        run: npm start &
+#      - name: Wait
+#        run: npx wait-on --timeout 5000 http://localhost:1234
+#      - name: Run tests
+#        run: npm test
+#      - name: Verify project version
+#        id: project-version
+#        run: |
+#          VERSION=$(jq -r '.version' package.json)
+#          echo "Found version: $VERSION"
+#          TAG="v${VERSION}"
+#          if git tag -l "$TAG" | grep -q "$TAG"; then
+#            echo "Error: Tag $TAG already exists."
+#            exit 1
+#          fi
+#          echo "Tag $TAG does not exist, proceeding."
+#          echo "TAG=$TAG" >> "$GITHUB_ENV"
+#          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
+#          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+#      - name: Generate build
+#        env:
+#          NODE_ENV: ${{ vars.NODE_ENV }}
+#        run: npm run build
+#      - name: Upload build archive
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: web
+#          path: dist
+#          compression-level: '9'
